//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHL_BaiKiemtraGiuKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LhlKHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LhlKHOA()
        {
            this.LHLSVs = new HashSet<LHLSV>();
        }
    
        public string LhlMaKH { get; set; }
        public string LhlTenKH { get; set; }
        public Nullable<bool> LhlTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LHLSV> LHLSVs { get; set; }
    }
}
