//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LHL_BaiKiemtraGiuKi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LHLSV
    {
        public string LhlMaSV { get; set; }
        public string LhlHoSv { get; set; }
        public string LhlTenSV { get; set; }
        public Nullable<System.DateTime> LhlNgaySinh { get; set; }
        public Nullable<bool> LhlPhai { get; set; }
        public string LhlPhone { get; set; }
        public string LhlEmail { get; set; }
        public string LhlMaKH { get; set; }
    
        public virtual LhlKHOA LhlKHOA { get; set; }
    }
}
